### ISSUE TITLE
Product-type field definition change Error

### ISSUE THREAD

**Issue by Franco10G** [labd/terraform-provider-commercetools#267] opened 2022-06-27 18:09 UTC
Hello, 

I had a weird error while changing some product-type fields:
<img width="717" alt="Captura de Pantalla 2022-06-27 a la(s) 15 07 02" src="https://user-images.githubusercontent.com/103056946/176007353-77794a01-201d-471f-8be3-8e86062eb391.png">

I don't think I did something wrong in TF so maybe it's a bug?
You can see the error log bellow,
Thank you in advance.

```
─────────────────────────────────────────────────────────────────────────────
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
  # commercetools_product_type.generic will be updated in-place
~ resource "commercetools_product_type" "generic" {
id          = "xxxxxx-xxxxxxx-xxxxxxx-xxxxxxx"
name        = "Generic product"
# (3 unchanged attributes hidden)
~attribute {
~label      = {
~"en-US" = "Lots" ->"Lot"
            }
~name       = "lots" ->"lot"
# (5 unchanged attributes hidden)
~type {
~name              = "set" ->"reference"
+reference_type_id = "key-value-document"
# (1 unchanged attribute hidden)
-element_type {
-name              = "reference" ->null
-reference_type_id = "key-value-document" ->null
-values            = {} ->null
                }
            }
        }
~attribute {
name       = "targets"
# (6 unchanged attributes hidden)
~type {
~name   = "text" ->"set"
# (1 unchanged attribute hidden)
+element_type {
+name = "text"
                }
            }
        }
# (45 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
commercetools_product_type.generic: Modifying... [id=xxxxxx-xxxxxxx-xxxxxxx-xxxxxxx]
╷
│Error: Plugin did not respond
│
│  with commercetools_product_type.generic,
│  on product_types.tf line 1, in resource "commercetools_product_type" "generic":
│   1: resource "commercetools_product_type" "generic" {
│
│The plugin encountered an error, and failed to respond to the
│plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│contain more details.
╵
Stack trace from the terraform-provider-commercetools_v1.2.1 plugin:
panic: runtime error: index out of range [0] with length 0
goroutine 13 [running]:
github.com/labd/terraform-provider-commercetools/commercetools.resourceProductTypeAttributeChangeActions({0xc0000fd200, 0x2f, 0x0?}, {0xc0000fcf00, 0x2f, 0xc0003828c0?})
	github.com/labd/terraform-provider-commercetools/commercetools/resource_product_type.go:527 +0x1d74
github.com/labd/terraform-provider-commercetools/commercetools.resourceProductTypeUpdate({0x1181f20?, 0xc0000887e0}, 0xc00045e300, {0x101be00?, 0xc00000c[498]()
	github.com/labd/terraform-provider-commercetools/commercetools/resource_product_type.go:397 +0x685
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000253c00, {0x1181f58, 0xc000197bc0}, 0xd?, {0x101be00, 0xc00000c498})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000253c00, {0x1181f58, 0xc000197bc0}, 0xc0000a6ea0, 0xc00045f880, {0x101be00, 0xc00000c498})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00036c498, {0x1181eb0?, 0xc000195d40?}, 0xc00047a870)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00034a6e0, {0x1181f58?, 0xc0001973e0?}, 0xc0002d60e0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xfe9ac0?, 0xc00034a6e0}, {0x1181f58, 0xc0001973e0}, 0xc000403[500](), 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000236a80, {0x11849c8, 0xc0003a49c0}, 0xc0000fbd40, 0xc0003819b0, 0x17afbe0, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000236a80, {0x11849c8, 0xc0003a49c0}, 0xc0000fbd40, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a
Error: The terraform-provider-commercetools_v1.2.1 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

**Comment by onur9** [comment] 2022-06-28 11:49
Thanks @Franco10G 

This seems to be a null value error. I'll send a fix for it.

That being said, I think your example still won't work. While trying to reproduce this error I noticed that we don't update reference attribute types. [This function](https://github.com/labd/terraform-provider-commercetools/blob/2115879afa9b1ca1aacb755831677ec06f7b0c13/commercetools/resource_product_type.go#L577) should also have a case for handling `AttributeReferenceType` types.

I am trying to figure out which product type action updates this value.

**Comment by Franco10G** [comment] 2022-06-28 13:38
Hi @onur9 thank you for the answer,
Now that you mention it, I think there is no action to modify the "type" property of a product-type attribute.
the only way I see this working is by deleting the attribute and re-creating it.
Thanks again for the help!

**Comment by onur9** [comment] 2022-06-28 14:28
@mvantellingen 

There is an action for [ProductTypeAddPlainEnumValueAction](https://github.com/labd/commercetools-go-sdk/blob/1676ca381fd254923b28b78b572c3756f52d7213/platform/types_product_type.go#L752) and [ProductTypeAddLocalizedEnumValueAction](https://github.com/labd/commercetools-go-sdk/blob/1676ca381fd254923b28b78b572c3756f52d7213/platform/types_product_type.go#L737) but nothing so far about references.

You can match it with `AttributeReferenceType`, but I am not sure which actions correspond to it.

**Comment by onur9** [comment] 2022-06-29 17:06
Hello @Franco10G 

Range error is fixed but I'll keep this one open until we figure out the reference type issue.

There seems to be another error which might be related to this. https://github.com/labd/terraform-provider-commercetools/issues/269

There are some change actions being applied [in here](https://github.com/labd/terraform-provider-commercetools/blob/main/commercetools/resource_product_type.go#L583), but it seems they are only produced for labels.

This function should be improved a little bit more to cover all the cases of attribute types.

**Comment by onur9** [comment] 2022-07-08 11:08
@Franco10G 

Yes, you're right. I think I mixed this up with something else. I'm closing this issue, as the actual bug is fixed now.

Thanks a lot!

**Closed by onur9** 2022-07-08 11:08 UTC
Labels: bug, resource_product_type
