### ISSUE TITLE
commercetools_subscription is started to fail after upgrade to 1.7.0 (1.6.9 too)

### ISSUE THREAD

**Issue by denisp13** [labd/terraform-provider-commercetools#372] opened 2023-05-26 21:58 UTC
**Information**
Terraform version: v1.3.2
Provider version: 1.7.0
Resource: commercetools_subscription 

**To Reproduce**
1. create a new commercetools_subscription  with connection to Azure Service Bus, eg
```hcl
resource "commercetools_subscription" "subscription" {
    key     = "test-subscription"

    destination {
        connection_string = "Endpoint=sb://dev-***-general-sb-euwe.servicebus.windows.net/;SharedAccessKeyName=coto-test;SharedAccessKey=****dME=;EntityPath=test-changes"
        type              = "AzureServiceBus"
    }

    format {
        type = "Platform"
    }
}
```

2. During the apply an error appears
<details><summary>Error</summary>
<p>

Terraform v1.3.4
on linux_amd64
module.commercetools_subscription.commercetools_subscription.subscription["coto-order-changes-subscription"]: Modifying... [id=b9e52068-fd77-44c2-a72e-81d3584a9f44]
╷
│ Error: Error updating subscription
│ 
│   with module.commercetools_subscription.commercetools_subscription.subscription["coto-order-changes-subscription"],
│   on ../modules/tf-commercetools/subscription/main.tf line 1, in resource "commercetools_subscription" "subscription":
│    1: resource "commercetools_subscription" "subscription" {
│ 
│ Could not update subscription, unexpected error: A test message could not
│ be delivered to this destination: AzureServiceBus
│ Endpoint=sb://dev-***-general-sb-euwe.servicebus.windows.net/;SharedAccessKeyName=coto-test;SharedAccessKey=****dME=;EntityPath=test-changes".
│ Please make sure your destination is correctly configured.
</p>
</details> 

The resource was successfully created with provider version - 1.5.1, the error is thrown on the version - 1.7.0 and 1.6.9

- We use Terraform Cloud as a remote backend
- There is no Network restriction on the SBS blocking the access

**Comment by denisp13** [comment] 2023-05-27 09:47
I tried to remove subscription object from the state and reimport it , following error is thrown 
```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-commercetools_v1.7.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 337 [running]:
github.com/labd/terraform-provider-commercetools/internal/resources/subscription.(*Subscription).setSecretValues(...)
        github.com/labd/terraform-provider-commercetools/internal/resources/subscription/model.go:82
github.com/labd/terraform-provider-commercetools/internal/resources/subscription.(*subscriptionResource).Read(0xc0007707b8, {0x2026120, 0xc000c1d3e0}, {{{{0x202b328, 0xc000909410}, {0x1c73200, 0xc0009090b0}}, {0x202cd08, 0xc0003a5180}}, 0xc00061c770, ...}, ...)
        github.com/labd/terraform-provider-commercetools/internal/resources/subscription/resource.go:338 +0x745
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0000ad340, {0x2026120, 0xc000c1d3e0}, 0xc000c1d4d0, 0xc0005e13f8)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_readresource.go:97 +0x617
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ReadResource(0xc0000ad340, {0x2026120?, 0xc000c1d290?}, 0xc000657b80)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto5server/server_readresource.go:53 +0x27b
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc0003e2330, 0xc0003e2390, {0xc000404760, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003acfa0, {0x2026120?, 0xc000c1c5a0?}, 0xc0005903c0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1e25c60?, 0xc0003acfa0}, {0x2026120, 0xc000c1c5a0}, 0xc000398230, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002821e0, {0x202b680, 0xc00050a820}, 0xc000b259e0, 0xc000421ce0, 0x276d530, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0002821e0, {0x202b680, 0xc00050a820}, 0xc000b259e0, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-commercetools_v1.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```
Please you urgent help is needed here!

**Comment by denisp13** [comment] 2023-05-30 11:10
@mvantellingen  this issue hits multiple users, can you please provide an update?

- https://github.com/labd/terraform-provider-commercetools/issues/360
- https://github.com/labd/terraform-provider-commercetools/issues/355

**Comment by okkevandereijk** [comment] 2023-05-30 15:03
@denisp13 I have tested your scenario by creating a new Azure Service Bus (ASB) environment. I have verified the following:
- When I use a `terraform apply` for your configuration with provider version 1.5.1, upgrade it to 1.7.0 and re-apply it again I can not reproduce your error. However, I do see the version number in Commercetools is increased (1 -> 2) and the subscription resource re-created. This is likely caused by the implementation of the `terraform-plugin-framework`: https://github.com/labd/terraform-provider-commercetools/pull/327. The error you see is likely from Commercetools and some kind of by an issue with the ASB at your side cause Commercetools does send a test message when it (re)creates a subscription

- When I re-import the terraform state I can re-produce that the error that the plugin is crashed. This is likely caused by the issue outlined here [here](https://github.com/labd/terraform-provider-commercetools/blob/165a57f8f24090cc45bb26a272471b954b7c41c9/internal/resources/subscription/model.go#LL196C26-L196C26). I am afraid restoring the secret key isn't possible while re-importing the state.

Is it possible for you to just to remove the terraform state and re-create the whole subscription again? This likely would solve the issue.

**Comment by okkevandereijk** [comment] 2023-06-02 08:02
@denisp13 Did you manage to fix it?

**Comment by demeyerthom** [comment] 2023-08-22 08:24
@denisp13 yeah, the handling of secrets in state are a bit wonkey, because commercetools does not actually send back the full secret as a security measure, which makes our state comparison break because the incoming state is not similar to the current state. 

This should have been fixed in newer versions, are you still running into this issue?

**Closed** 2023-08-30 07:20 UTC
Labels: bug, awaiting-response
