### ISSUE TITLE
Support for api extensions triggered by "business-unit" events

### ISSUE THREAD

**Issue by tosh79kt** [labd/terraform-provider-commercetools#323] opened 2022-11-16 13:40 UTC
Hi everybody,

are there plans to add support for api-extensions that get triggered by business-unit creates or updates?

Currently I need to add those via postman which is less than optimal. Looking forward hearing from you.

Thanks for the great work!
Tobias

**Comment by pimvernooij** [comment] 2022-11-16 15:09
Hi Tobias,

Thanks for your request. We did see the new feature in commercetools as well, however at this moment we don't have a concrete use case for that in our projects, but i'm sure that we'll start using the concept at some point sooner or later. When we do, we most likely will implement it. But it might take a while.

I did see that the [commercetools-go-sdk](https://github.com/labd/commercetools-go-sdk/commit/c4790cd337a275f0c0fffd95fb1c860112483026) was recently regenerated and many additions around Business Units were added, which can be used to implement the necessary TF resources.

Best,
Pim

**Comment by tosh79kt** [comment] 2022-11-17 09:38
Hey Pim,
thanks for the explanation. I'd be happy to provide a small PR adding support for business-units. At least for the extensions-part. 

I can see, that the commercetools-go-sdk has been regenerated, adding support for more stuff. However, this new, regenerated version has not been tagged, yet, making it impossible (I guess) to reference it from this provider.

What I would do now:
1. Create an issue over at https://github.com/labd/commercetools-go-sdk to ask for a new tag (e.g. v1.2.0)
2. When the tag has been created: create a new PR for the terraform-provider adding the requested support

What do you think?

Best regards!
Tobias

**Comment by pimvernooij** [comment] 2022-11-22 10:13
Great! Yes we can release a new version of the SDK soon.
In the mean time you could already implement the feature of course, using the main branch of the SDK locally.

**Comment by mvantellingen** [comment] 2022-11-22 11:43
I've just regenerated the go sdk with the latest changes and tagged it with v1.2.0

See https://github.com/labd/commercetools-go-sdk/tree/v1.2.0

**Comment by tosh79kt** [comment] 2022-11-25 09:46
Thanks for the heads-up. We are planning to create a pull request shortly.

**Comment by mschuette-kpunkt** [comment] 2022-12-21 14:33
Hi Guys, 
I'm trying to create an pull request, but I need to update the sdk, so the new `platform.ExtensionResourceTypeIdBusinessUnit` is supported and found in `platform`. But the command from the docs for updating sdk `make update-sdk` does throw error `make: *** No rule to make target 'update-sdk'.  Stop.`
Can you help me, what I'm missing?
Thanks!

**Comment by pimvernooij** [comment] 2022-12-21 14:58
That command is not available anymore. Though updating the SDK should be straightforward by updating the dependency here: https://github.com/labd/terraform-provider-commercetools/blob/main/go.mod#L8

**Comment by mschuette-kpunkt** [comment] 2022-12-21 15:01
Thanks for the quick reply! As I mentioned in the edit, I updated it successfully but get new errors now, like:
```
commercetools\resource_product_discount.go:343:11: cannot use money (variable of type []platform.CentPrecisionMoneyDraft) as type []platform.Money in struct literal
commercetools\resource_product_type.go:962:22: cannot use platform.ReferenceTypeId(ref) (value of type platform.ReferenceTypeId) as type platform.AttributeReferenceTypeId in struct literal
commercetools\resource_shipping_zone_rate.go:598:20: cannot use tierMap["score"].(float64) (comma, ok expression of type float64) as type int in struct literal
commercetools\resource_subscription.go:460:18: cannot use dst["access_key"].(string) (comma, ok expression of type string) as type *string in struct literal
commercetools\resource_subscription.go:461:18: cannot use dst["access_secret"].(string) (comma, ok expression of type string) as type *string in struct literal
commercetools\resource_subscription.go:466:18: cannot use dst["access_key"].(string) (comma, ok expression of type string) as type *string in struct literal
commercetools\resource_subscription.go:467:18: cannot use dst["access_secret"].(string) (comma, ok expression of type string) as type *string in struct literal
commercetools\resource_subscription.go:503:17: cannot use current.AccessSecret (variable of type *string) as type string in assignment
commercetools\resource_subscription.go:505:17: cannot use current.AccessSecret (variable of type *string) as type string in assignment
commercetools\resource_subscription.go:537:21: cannot use v.AccessKey (variable of type *string) as type string in map literal
commercetools\resource_subscription.go:537:21: too many errors
```
They appear without other changes than updating...

**Comment by pimvernooij** [comment] 2022-12-21 15:07
This is caused by some backwards incompatible type changes in the SDK - which in turn is caused by changes in the commercetools spec that is used for generating the SDK. Unfortunately we can't prevent that, so those would need to be fixed in order to get the provider compiled I'm afraid :-).

**Comment by mschuette-kpunkt** [comment] 2022-12-21 15:12
Yeah, thought so. I just hoped It would really only be the switch statement :D 
Thanks anyway!

**Comment by pimvernooij** [comment] 2022-12-21 15:14
I did too :-)

**Comment by mvantellingen** [comment] 2022-12-21 16:01
Just updated the main branch to work with the changes in the SDK. So you should be good to go

**Comment by mschuette-kpunkt** [comment] 2022-12-22 10:54
Thank you very much! Now I was able to do the change and test ist with my project.
Pull request: https://github.com/labd/terraform-provider-commercetools/pull/325

**Closed** 2022-12-23 16:54 UTC
