### ISSUE TITLE
Product type attribute type change doesn't create attribute

### ISSUE THREAD

**Issue by davidweterings** [labd/terraform-provider-commercetools#116] opened 2020-04-09 13:08 UTC
F.e. changing from 'text' to 'ltext'. This would involve deleting the attribute and adding it again, since CT doesn't support changing the type. It would also mean the data on the original attribute is lost (but you're changing the type, so perhaps this is acceptable?).

**Comment by mvantellingen** [comment] 2022-07-05 21:25
This seems to be a duplicate of #40 and I believe we now raise an error in terraform

**Comment by mvantellingen** [comment] 2022-07-08 08:43
This raises an error now since this is not supported in commercetools

**Closed by mvantellingen** 2022-07-08 08:43 UTC
Labels: enhancement, resource_product_type
